/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PackageDetails = IDL.Record({
  'weight' : IDL.Float64,
  'description' : IDL.Text,
  'dimensions' : IDL.Text,
});
export const PhoneNumber = IDL.Text;
export const Pincode = IDL.Text;
export const Person = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : PhoneNumber,
  'pincode' : Pincode,
});
export const ShippingOption = IDL.Variant({
  'express' : IDL.Null,
  'overnight' : IDL.Null,
  'standard' : IDL.Null,
});
export const CreateBookingRequest = IDL.Record({
  'destination' : IDL.Text,
  'package' : PackageDetails,
  'sender' : Person,
  'shippingOption' : ShippingOption,
  'receiver' : Person,
});
export const ParcelStatus = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'inTransit' : IDL.Null,
  'delivered' : IDL.Null,
  'queued' : IDL.Null,
});
export const TrackingNumber = IDL.Text;
export const Time = IDL.Int;
export const BookingConfirmation = IDL.Record({
  'status' : ParcelStatus,
  'trackingNumber' : TrackingNumber,
  'bookingId' : IDL.Nat,
  'createdAt' : Time,
  'estimatedDelivery' : IDL.Text,
});
export const TrackingUpdate = IDL.Record({
  'status' : ParcelStatus,
  'note' : IDL.Text,
  'timestamp' : Time,
  'location' : IDL.Text,
});
export const Booking = IDL.Record({
  'trackingNumber' : TrackingNumber,
  'destination' : IDL.Text,
  'bookingId' : IDL.Nat,
  'package' : PackageDetails,
  'createdAt' : Time,
  'sender' : Person,
  'shippingOption' : ShippingOption,
  'trackingUpdates' : IDL.Vec(TrackingUpdate),
  'receiver' : Person,
  'currentStatus' : ParcelStatus,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : PhoneNumber,
});
export const UpdateStatusRequest = IDL.Record({
  'status' : ParcelStatus,
  'note' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([CreateBookingRequest], [BookingConfirmation], []),
  'getActiveTrackingNumbers' : IDL.Func(
      [],
      [IDL.Vec(TrackingNumber)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStatusHistory' : IDL.Func(
      [TrackingNumber],
      [IDL.Vec(TrackingUpdate)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDelivered' : IDL.Func([TrackingNumber], [IDL.Bool], ['query']),
  'isTrackingNumberValid' : IDL.Func([TrackingNumber], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackParcel' : IDL.Func([TrackingNumber], [Booking], ['query']),
  'updateParcelStatus' : IDL.Func(
      [TrackingNumber, UpdateStatusRequest],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PackageDetails = IDL.Record({
    'weight' : IDL.Float64,
    'description' : IDL.Text,
    'dimensions' : IDL.Text,
  });
  const PhoneNumber = IDL.Text;
  const Pincode = IDL.Text;
  const Person = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : PhoneNumber,
    'pincode' : Pincode,
  });
  const ShippingOption = IDL.Variant({
    'express' : IDL.Null,
    'overnight' : IDL.Null,
    'standard' : IDL.Null,
  });
  const CreateBookingRequest = IDL.Record({
    'destination' : IDL.Text,
    'package' : PackageDetails,
    'sender' : Person,
    'shippingOption' : ShippingOption,
    'receiver' : Person,
  });
  const ParcelStatus = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'inTransit' : IDL.Null,
    'delivered' : IDL.Null,
    'queued' : IDL.Null,
  });
  const TrackingNumber = IDL.Text;
  const Time = IDL.Int;
  const BookingConfirmation = IDL.Record({
    'status' : ParcelStatus,
    'trackingNumber' : TrackingNumber,
    'bookingId' : IDL.Nat,
    'createdAt' : Time,
    'estimatedDelivery' : IDL.Text,
  });
  const TrackingUpdate = IDL.Record({
    'status' : ParcelStatus,
    'note' : IDL.Text,
    'timestamp' : Time,
    'location' : IDL.Text,
  });
  const Booking = IDL.Record({
    'trackingNumber' : TrackingNumber,
    'destination' : IDL.Text,
    'bookingId' : IDL.Nat,
    'package' : PackageDetails,
    'createdAt' : Time,
    'sender' : Person,
    'shippingOption' : ShippingOption,
    'trackingUpdates' : IDL.Vec(TrackingUpdate),
    'receiver' : Person,
    'currentStatus' : ParcelStatus,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const UpdateStatusRequest = IDL.Record({
    'status' : ParcelStatus,
    'note' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [CreateBookingRequest],
        [BookingConfirmation],
        [],
      ),
    'getActiveTrackingNumbers' : IDL.Func(
        [],
        [IDL.Vec(TrackingNumber)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStatusHistory' : IDL.Func(
        [TrackingNumber],
        [IDL.Vec(TrackingUpdate)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDelivered' : IDL.Func([TrackingNumber], [IDL.Bool], ['query']),
    'isTrackingNumberValid' : IDL.Func([TrackingNumber], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackParcel' : IDL.Func([TrackingNumber], [Booking], ['query']),
    'updateParcelStatus' : IDL.Func(
        [TrackingNumber, UpdateStatusRequest],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };