/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'trackingNumber' : TrackingNumber,
  'destination' : string,
  'bookingId' : bigint,
  'package' : PackageDetails,
  'createdAt' : Time,
  'sender' : Person,
  'shippingOption' : ShippingOption,
  'trackingUpdates' : Array<TrackingUpdate>,
  'receiver' : Person,
  'currentStatus' : ParcelStatus,
}
export interface BookingConfirmation {
  'status' : ParcelStatus,
  'trackingNumber' : TrackingNumber,
  'bookingId' : bigint,
  'createdAt' : Time,
  'estimatedDelivery' : string,
}
export interface CreateBookingRequest {
  'destination' : string,
  'package' : PackageDetails,
  'sender' : Person,
  'shippingOption' : ShippingOption,
  'receiver' : Person,
}
export interface PackageDetails {
  'weight' : number,
  'description' : string,
  'dimensions' : string,
}
export type ParcelStatus = { 'outForDelivery' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'queued' : null };
export interface Person {
  'name' : string,
  'address' : string,
  'phone' : PhoneNumber,
  'pincode' : Pincode,
}
export type PhoneNumber = string;
export type Pincode = string;
export type ShippingOption = { 'express' : null } |
  { 'overnight' : null } |
  { 'standard' : null };
export type Time = bigint;
export type TrackingNumber = string;
export interface TrackingUpdate {
  'status' : ParcelStatus,
  'note' : string,
  'timestamp' : Time,
  'location' : string,
}
export interface UpdateStatusRequest {
  'status' : ParcelStatus,
  'note' : string,
  'location' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : PhoneNumber,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[CreateBookingRequest], BookingConfirmation>,
  'getActiveTrackingNumbers' : ActorMethod<[], Array<TrackingNumber>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStatusHistory' : ActorMethod<[TrackingNumber], Array<TrackingUpdate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDelivered' : ActorMethod<[TrackingNumber], boolean>,
  'isTrackingNumberValid' : ActorMethod<[TrackingNumber], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'trackParcel' : ActorMethod<[TrackingNumber], Booking>,
  'updateParcelStatus' : ActorMethod<
    [TrackingNumber, UpdateStatusRequest],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];