/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateBookingRequest {
    destination: string;
    package: PackageDetails;
    sender: Person;
    shippingOption: ShippingOption;
    receiver: Person;
}
export type Time = bigint;
export interface UpdateStatusRequest {
    status: ParcelStatus;
    note: string;
    location: string;
}
export type TrackingNumber = string;
export type Pincode = string;
export interface BookingConfirmation {
    status: ParcelStatus;
    trackingNumber: TrackingNumber;
    bookingId: bigint;
    createdAt: Time;
    estimatedDelivery: string;
}
export interface PackageDetails {
    weight: number;
    description: string;
    dimensions: string;
}
export type PhoneNumber = string;
export interface TrackingUpdate {
    status: ParcelStatus;
    note: string;
    timestamp: Time;
    location: string;
}
export interface Booking {
    trackingNumber: TrackingNumber;
    destination: string;
    bookingId: bigint;
    package: PackageDetails;
    createdAt: Time;
    sender: Person;
    shippingOption: ShippingOption;
    trackingUpdates: Array<TrackingUpdate>;
    receiver: Person;
    currentStatus: ParcelStatus;
}
export interface Person {
    name: string;
    address: string;
    phone: PhoneNumber;
    pincode: Pincode;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: PhoneNumber;
}
export enum ParcelStatus {
    outForDelivery = "outForDelivery",
    inTransit = "inTransit",
    delivered = "delivered",
    queued = "queued"
}
export enum ShippingOption {
    express = "express",
    overnight = "overnight",
    standard = "standard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(request: CreateBookingRequest): Promise<BookingConfirmation>;
    getActiveTrackingNumbers(): Promise<Array<TrackingNumber>>;
    getAllBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStatusHistory(trackingNumber: TrackingNumber): Promise<Array<TrackingUpdate>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(): Promise<UserRole>;
    initializeAccessControl(): Promise<void>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isDelivered(trackingNumber: TrackingNumber): Promise<boolean>;
    isTrackingNumberValid(trackingNumber: TrackingNumber): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    trackParcel(trackingNumber: TrackingNumber): Promise<Booking>;
    updateParcelStatus(trackingNumber: TrackingNumber, update: UpdateStatusRequest): Promise<void>;
}
import type { Booking as _Booking, BookingConfirmation as _BookingConfirmation, CreateBookingRequest as _CreateBookingRequest, PackageDetails as _PackageDetails, ParcelStatus as _ParcelStatus, Person as _Person, ShippingOption as _ShippingOption, Time as _Time, TrackingNumber as _TrackingNumber, TrackingUpdate as _TrackingUpdate, UpdateStatusRequest as _UpdateStatusRequest, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: CreateBookingRequest): Promise<BookingConfirmation> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_CreateBookingRequest_n3(this.uploadFile, this.downloadFile, arg0));
                return from_candid_BookingConfirmation_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_CreateBookingRequest_n3(this.uploadFile, this.downloadFile, arg0));
            return from_candid_BookingConfirmation_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getActiveTrackingNumbers(): Promise<Array<TrackingNumber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTrackingNumbers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTrackingNumbers();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStatusHistory(arg0: TrackingNumber): Promise<Array<TrackingUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatusHistory(arg0);
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatusHistory(arg0);
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_UserRole_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_UserRole_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isDelivered(arg0: TrackingNumber): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDelivered(arg0);
            return result;
        }
    }
    async isTrackingNumberValid(arg0: TrackingNumber): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTrackingNumberValid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTrackingNumberValid(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async trackParcel(arg0: TrackingNumber): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.trackParcel(arg0);
                return from_candid_Booking_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackParcel(arg0);
            return from_candid_Booking_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateParcelStatus(arg0: TrackingNumber, arg1: UpdateStatusRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParcelStatus(arg0, to_candid_UpdateStatusRequest_n22(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParcelStatus(arg0, to_candid_UpdateStatusRequest_n22(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingConfirmation_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingConfirmation): BookingConfirmation {
    return from_candid_record_n8(uploadFile, downloadFile, value);
}
function from_candid_Booking_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n13(uploadFile, downloadFile, value);
}
function from_candid_ParcelStatus_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParcelStatus): ParcelStatus {
    return from_candid_variant_n10(uploadFile, downloadFile, value);
}
function from_candid_ShippingOption_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShippingOption): ShippingOption {
    return from_candid_variant_n15(uploadFile, downloadFile, value);
}
function from_candid_TrackingUpdate_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackingUpdate): TrackingUpdate {
    return from_candid_record_n18(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(uploadFile, downloadFile, value);
}
function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trackingNumber: _TrackingNumber;
    destination: string;
    bookingId: bigint;
    package: _PackageDetails;
    createdAt: _Time;
    sender: _Person;
    shippingOption: _ShippingOption;
    trackingUpdates: Array<_TrackingUpdate>;
    receiver: _Person;
    currentStatus: _ParcelStatus;
}): {
    trackingNumber: TrackingNumber;
    destination: string;
    bookingId: bigint;
    package: PackageDetails;
    createdAt: Time;
    sender: Person;
    shippingOption: ShippingOption;
    trackingUpdates: Array<TrackingUpdate>;
    receiver: Person;
    currentStatus: ParcelStatus;
} {
    return {
        trackingNumber: value.trackingNumber,
        destination: value.destination,
        bookingId: value.bookingId,
        package: value.package,
        createdAt: value.createdAt,
        sender: value.sender,
        shippingOption: from_candid_ShippingOption_n14(uploadFile, downloadFile, value.shippingOption),
        trackingUpdates: from_candid_vec_n16(uploadFile, downloadFile, value.trackingUpdates),
        receiver: value.receiver,
        currentStatus: from_candid_ParcelStatus_n9(uploadFile, downloadFile, value.currentStatus)
    };
}
function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ParcelStatus;
    note: string;
    timestamp: _Time;
    location: string;
}): {
    status: ParcelStatus;
    note: string;
    timestamp: Time;
    location: string;
} {
    return {
        status: from_candid_ParcelStatus_n9(uploadFile, downloadFile, value.status),
        note: value.note,
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ParcelStatus;
    trackingNumber: _TrackingNumber;
    bookingId: bigint;
    createdAt: _Time;
    estimatedDelivery: string;
}): {
    status: ParcelStatus;
    trackingNumber: TrackingNumber;
    bookingId: bigint;
    createdAt: Time;
    estimatedDelivery: string;
} {
    return {
        status: from_candid_ParcelStatus_n9(uploadFile, downloadFile, value.status),
        trackingNumber: value.trackingNumber,
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        estimatedDelivery: value.estimatedDelivery
    };
}
function from_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outForDelivery: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    queued: null;
}): ParcelStatus {
    return "outForDelivery" in value ? ParcelStatus.outForDelivery : "inTransit" in value ? ParcelStatus.inTransit : "delivered" in value ? ParcelStatus.delivered : "queued" in value ? ParcelStatus.queued : value;
}
function from_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    express: null;
} | {
    overnight: null;
} | {
    standard: null;
}): ShippingOption {
    return "express" in value ? ShippingOption.express : "overnight" in value ? ShippingOption.overnight : "standard" in value ? ShippingOption.standard : value;
}
function from_candid_variant_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n12(uploadFile, downloadFile, x));
}
function from_candid_vec_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackingUpdate>): Array<TrackingUpdate> {
    return value.map((x)=>from_candid_TrackingUpdate_n17(uploadFile, downloadFile, x));
}
function to_candid_CreateBookingRequest_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingRequest): _CreateBookingRequest {
    return to_candid_record_n4(uploadFile, downloadFile, value);
}
function to_candid_ParcelStatus_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelStatus): _ParcelStatus {
    return to_candid_variant_n25(uploadFile, downloadFile, value);
}
function to_candid_ShippingOption_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShippingOption): _ShippingOption {
    return to_candid_variant_n6(uploadFile, downloadFile, value);
}
function to_candid_UpdateStatusRequest_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStatusRequest): _UpdateStatusRequest {
    return to_candid_record_n23(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ParcelStatus;
    note: string;
    location: string;
}): {
    status: _ParcelStatus;
    note: string;
    location: string;
} {
    return {
        status: to_candid_ParcelStatus_n24(uploadFile, downloadFile, value.status),
        note: value.note,
        location: value.location
    };
}
function to_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    package: PackageDetails;
    sender: Person;
    shippingOption: ShippingOption;
    receiver: Person;
}): {
    destination: string;
    package: _PackageDetails;
    sender: _Person;
    shippingOption: _ShippingOption;
    receiver: _Person;
} {
    return {
        destination: value.destination,
        package: value.package,
        sender: value.sender,
        shippingOption: to_candid_ShippingOption_n5(uploadFile, downloadFile, value.shippingOption),
        receiver: value.receiver
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParcelStatus): {
    outForDelivery: null;
} | {
    inTransit: null;
} | {
    delivered: null;
} | {
    queued: null;
} {
    return value == ParcelStatus.outForDelivery ? {
        outForDelivery: null
    } : value == ParcelStatus.inTransit ? {
        inTransit: null
    } : value == ParcelStatus.delivered ? {
        delivered: null
    } : value == ParcelStatus.queued ? {
        queued: null
    } : value;
}
function to_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShippingOption): {
    express: null;
} | {
    overnight: null;
} | {
    standard: null;
} {
    return value == ShippingOption.express ? {
        express: null
    } : value == ShippingOption.overnight ? {
        overnight: null
    } : value == ShippingOption.standard ? {
        standard: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
